import { Injectable } from '@nestjs/common';

@Injectable()
export class RatehawkMockService {
  private mockHotels = [
    // Gulf - Riyadh
    {
      id: 'hotel-riyadh-1',
      name: 'فندق الفيصلية الرياض',
      nameEn: 'Al Faisaliah Hotel Riyadh',
      cityId: 'riyadh',
      stars: 5,
      rating: 4.7,
      reviewCount: 1243,
      pricePerNight: 1200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'طريق الملك فهد، الرياض',
      addressEn: 'King Fahd Road, Riyadh',
      amenities: ['مسبح', 'سبا', 'مطعم', 'واي فاي مجاني', 'موقف سيارات'],
      lat: 24.6900,
      lng: 46.6851,
    },
    {
      id: 'hotel-riyadh-2',
      name: 'فندق برج رافال الرياض',
      nameEn: 'Rafal Tower Hotel Riyadh',
      cityId: 'riyadh',
      stars: 4,
      rating: 4.5,
      reviewCount: 856,
      pricePerNight: 850,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
      address: 'حي السفارات، الرياض',
      addressEn: 'Diplomatic Quarter, Riyadh',
      amenities: ['مسبح', 'صالة رياضية', 'واي فاي مجاني'],
      lat: 24.7136,
      lng: 46.6753,
    },
    {
      id: 'hotel-riyadh-3',
      name: 'فندق ريتز كارلتون الرياض',
      nameEn: 'The Ritz-Carlton Riyadh',
      cityId: 'riyadh',
      stars: 5,
      rating: 4.8,
      reviewCount: 2134,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      address: 'طريق المعذر، الرياض',
      addressEn: 'Al Mather Road, Riyadh',
      amenities: ['مسبح', 'سبا', 'مطعم', 'واي فاي مجاني', 'صالة رياضية', 'خدمة الغرف'],
      lat: 24.7249,
      lng: 46.6582,
    },
    // Gulf - Jeddah
    {
      id: 'hotel-jeddah-1',
      name: 'فندق كراون بلازا جدة',
      nameEn: 'Crowne Plaza Jeddah',
      cityId: 'jeddah',
      stars: 5,
      rating: 4.6,
      reviewCount: 1567,
      pricePerNight: 1100,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
      address: 'طريق الملك عبدالعزيز، جدة',
      addressEn: 'King Abdulaziz Road, Jeddah',
      amenities: ['إطلالة على البحر', 'مسبح', 'مطعم', 'واي فاي مجاني'],
      lat: 21.5169,
      lng: 39.1748,
    },
    {
      id: 'hotel-jeddah-2',
      name: 'فندق هيلتون جدة',
      nameEn: 'Hilton Jeddah',
      cityId: 'jeddah',
      stars: 5,
      rating: 4.5,
      reviewCount: 1823,
      pricePerNight: 950,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
      address: 'شارع الكورنيش، جدة',
      addressEn: 'Corniche Road, Jeddah',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'مطعم', 'واي فاي مجاني'],
      lat: 21.5285,
      lng: 39.1432,
    },
    // Gulf - Dubai
    {
      id: 'hotel-dubai-1',
      name: 'برج العرب جميرا',
      nameEn: 'Burj Al Arab Jumeirah',
      cityId: 'dubai',
      stars: 5,
      rating: 4.9,
      reviewCount: 3421,
      pricePerNight: 5000,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
      address: 'Jumeirah Street, Dubai',
      addressEn: 'Jumeirah Street, Dubai',
      amenities: ['شاطئ خاص', 'مطاعم فاخرة', 'سبا عالمي', 'مسبح لا متناهي'],
      lat: 25.1412,
      lng: 55.1853,
    },
    {
      id: 'hotel-dubai-2',
      name: 'فندق أتلانتس النخلة',
      nameEn: 'Atlantis The Palm',
      cityId: 'dubai',
      stars: 5,
      rating: 4.7,
      reviewCount: 4532,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: 'نخلة جميرا، دبي',
      addressEn: 'Palm Jumeirah, Dubai',
      amenities: ['أكواريوم', 'حديقة مائية', 'شاطئ خاص', 'مطاعم متنوعة'],
      lat: 25.1304,
      lng: 55.1172,
    },
    {
      id: 'hotel-dubai-3',
      name: 'فندق أرماني دبي',
      nameEn: 'Armani Hotel Dubai',
      cityId: 'dubai',
      stars: 5,
      rating: 4.8,
      reviewCount: 2156,
      pricePerNight: 3200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1606046604972-77cc76aee944?w=800',
      address: 'برج خليفة، دبي',
      addressEn: 'Burj Khalifa, Dubai',
      amenities: ['سبا', 'مطاعم فاخرة', 'واي فاي مجاني', 'إطلالة بانورامية'],
      lat: 25.1972,
      lng: 55.2744,
    },
    // Gulf - Makkah
    {
      id: 'hotel-makkah-1',
      name: 'فندق فيرمونت برج الساعة',
      nameEn: 'Fairmont Clock Tower',
      cityId: 'makkah',
      stars: 5,
      rating: 4.8,
      reviewCount: 5621,
      pricePerNight: 2500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=800',
      address: 'أبراج البيت، مكة المكرمة',
      addressEn: 'Abraj Al-Bait, Makkah',
      amenities: ['إطلالة على الحرم', 'مطاعم', 'واي فاي مجاني', 'خدمة الغرف'],
      lat: 21.4189,
      lng: 39.8252,
    },
    {
      id: 'hotel-makkah-2',
      name: 'فندق رافلز مكة',
      nameEn: 'Raffles Makkah Palace',
      cityId: 'makkah',
      stars: 5,
      rating: 4.7,
      reviewCount: 3245,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'أبراج البيت، مكة المكرمة',
      addressEn: 'Abraj Al-Bait, Makkah',
      amenities: ['إطلالة على الحرم', 'سبا', 'مطاعم', 'خدمة الخادم الشخصي'],
      lat: 21.4195,
      lng: 39.8263,
    },
    {
      id: 'hotel-makkah-3',
      name: 'فندق سويس أوتيل مكة',
      nameEn: 'Swissotel Makkah',
      cityId: 'makkah',
      stars: 5,
      rating: 4.6,
      reviewCount: 2876,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800',
      address: 'أبراج البيت، مكة المكرمة',
      addressEn: 'Abraj Al-Bait, Makkah',
      amenities: ['إطلالة على الحرم', 'مطاعم', 'واي فاي مجاني', 'مواقف سيارات'],
      lat: 21.4201,
      lng: 39.8271,
    },
    // Gulf - Madinah
    {
      id: 'hotel-madinah-1',
      name: 'فندق أوبروي المدينة',
      nameEn: 'The Oberoi Madinah',
      cityId: 'madinah',
      stars: 5,
      rating: 4.9,
      reviewCount: 2134,
      pricePerNight: 1600,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1542816417-0983c9c9ad53?w=800',
      address: 'المنطقة المركزية، المدينة المنورة',
      addressEn: 'Central Area, Madinah',
      amenities: ['إطلالة على الحرم النبوي', 'مطاعم', 'سبا', 'واي فاي مجاني'],
      lat: 24.4672,
      lng: 39.6114,
    },
    {
      id: 'hotel-madinah-2',
      name: 'فندق دار الإيمان جراند',
      nameEn: 'Dar Al Iman Grand',
      cityId: 'madinah',
      stars: 4,
      rating: 4.5,
      reviewCount: 1876,
      pricePerNight: 950,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800',
      address: 'شارع السلام، المدينة المنورة',
      addressEn: 'Al Salam Street, Madinah',
      amenities: ['قريب من الحرم', 'مطعم', 'واي فاي مجاني'],
      lat: 24.4689,
      lng: 39.6098,
    },
    // Gulf - Doha
    {
      id: 'hotel-doha-1',
      name: 'فندق سانت ريجيس الدوحة',
      nameEn: 'The St. Regis Doha',
      cityId: 'doha',
      stars: 5,
      rating: 4.8,
      reviewCount: 1654,
      pricePerNight: 1400,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1549920867-0066d8c3e3e9?w=800',
      address: 'الخليج الغربي، الدوحة',
      addressEn: 'West Bay, Doha',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'مطاعم فاخرة'],
      lat: 25.3215,
      lng: 51.5310,
    },
    {
      id: 'hotel-doha-2',
      name: 'فندق شانغريلا الدوحة',
      nameEn: 'Shangri-La Doha',
      cityId: 'doha',
      stars: 5,
      rating: 4.7,
      reviewCount: 1423,
      pricePerNight: 1200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      address: 'الخليج الغربي، الدوحة',
      addressEn: 'West Bay, Doha',
      amenities: ['مسبح', 'سبا', 'صالة رياضية', 'مطاعم'],
      lat: 25.3198,
      lng: 51.5287,
    },
    // Gulf - Abu Dhabi
    {
      id: 'hotel-abu-dhabi-1',
      name: 'قصر الإمارات',
      nameEn: 'Emirates Palace',
      cityId: 'abu-dhabi',
      stars: 5,
      rating: 4.9,
      reviewCount: 3876,
      pricePerNight: 3500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1611605645802-c21be743c321?w=800',
      address: 'شارع الكورنيش، أبوظبي',
      addressEn: 'Corniche Road, Abu Dhabi',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'مطاعم فاخرة', 'ملاعب تنس'],
      lat: 24.4614,
      lng: 54.3171,
    },
    {
      id: 'hotel-abu-dhabi-2',
      name: 'فندق جميرا أبوظبي',
      nameEn: 'Jumeirah at Saadiyat Island',
      cityId: 'abu-dhabi',
      stars: 5,
      rating: 4.8,
      reviewCount: 2143,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
      address: 'جزيرة السعديات، أبوظبي',
      addressEn: 'Saadiyat Island, Abu Dhabi',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'نادي للأطفال'],
      lat: 24.5362,
      lng: 54.4291,
    },
    // Gulf - Kuwait
    {
      id: 'hotel-kuwait-1',
      name: 'فندق فور سيزونز الكويت',
      nameEn: 'Four Seasons Kuwait',
      cityId: 'kuwait',
      stars: 5,
      rating: 4.7,
      reviewCount: 987,
      pricePerNight: 1100,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?w=800',
      address: 'برج الحمراء، الكويت',
      addressEn: 'Al Hamra Tower, Kuwait City',
      amenities: ['مسبح', 'سبا', 'مطاعم', 'صالة رياضية'],
      lat: 29.3759,
      lng: 47.9774,
    },
    {
      id: 'hotel-kuwait-2',
      name: 'فندق جميرا الكويت',
      nameEn: 'Jumeirah Messilah Beach Hotel',
      cityId: 'kuwait',
      stars: 5,
      rating: 4.6,
      reviewCount: 1234,
      pricePerNight: 980,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: 'المسيلة، الكويت',
      addressEn: 'Messilah, Kuwait City',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'ملاعب رياضية'],
      lat: 29.2785,
      lng: 48.0869,
    },
    // Gulf - Muscat
    {
      id: 'hotel-muscat-1',
      name: 'فندق شانغريلا مسقط',
      nameEn: 'Shangri-La Barr Al Jissah',
      cityId: 'muscat',
      stars: 5,
      rating: 4.8,
      reviewCount: 1543,
      pricePerNight: 1300,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1560604155-98f00ebe0b00?w=800',
      address: 'بر الجصة، مسقط',
      addressEn: 'Barr Al Jissah, Muscat',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'رياضات مائية'],
      lat: 23.5437,
      lng: 58.6348,
    },
    {
      id: 'hotel-muscat-2',
      name: 'فندق الريتز كارلتون مسقط',
      nameEn: 'The Ritz-Carlton Al Bustan Palace',
      cityId: 'muscat',
      stars: 5,
      rating: 4.9,
      reviewCount: 1876,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'البستان، مسقط',
      addressEn: 'Al Bustan, Muscat',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'حدائق استوائية'],
      lat: 23.5789,
      lng: 58.5943,
    },
    // Gulf - Bahrain
    {
      id: 'hotel-bahrain-1',
      name: 'فندق فور سيزونز البحرين',
      nameEn: 'Four Seasons Bahrain Bay',
      cityId: 'bahrain',
      stars: 5,
      rating: 4.8,
      reviewCount: 1234,
      pricePerNight: 1200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1559564484-e48b3e040ff4?w=800',
      address: 'خليج البحرين، المنامة',
      addressEn: 'Bahrain Bay, Manama',
      amenities: ['شاطئ خاص', 'مسبح', 'سبا', 'مطاعم فاخرة'],
      lat: 26.2423,
      lng: 50.5832,
    },
    {
      id: 'hotel-bahrain-2',
      name: 'فندق ريتز كارلتون البحرين',
      nameEn: 'The Ritz-Carlton Bahrain',
      cityId: 'bahrain',
      stars: 5,
      rating: 4.7,
      reviewCount: 1567,
      pricePerNight: 1100,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      address: 'المنامة، البحرين',
      addressEn: 'Manama, Bahrain',
      amenities: ['شاطئ', 'مسبح', 'سبا', 'نادي للأطفال'],
      lat: 26.2156,
      lng: 50.5489,
    },
    // Europe - Paris
    {
      id: 'hotel-paris-1',
      name: 'فندق بلازا أتيني',
      nameEn: 'Plaza Athénée Paris',
      cityId: 'paris',
      stars: 5,
      rating: 4.9,
      reviewCount: 2876,
      pricePerNight: 4500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800',
      address: '25 Avenue Montaigne, Paris',
      addressEn: '25 Avenue Montaigne, Paris',
      amenities: ['مطعم ميشلان', 'سبا', 'إطلالة على برج إيفل', 'خدمة الخادم'],
      lat: 48.8661,
      lng: 2.3046,
    },
    {
      id: 'hotel-paris-2',
      name: 'فندق لو موريس',
      nameEn: 'Le Meurice Paris',
      cityId: 'paris',
      stars: 5,
      rating: 4.8,
      reviewCount: 2134,
      pricePerNight: 3800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800',
      address: '228 Rue de Rivoli, Paris',
      addressEn: '228 Rue de Rivoli, Paris',
      amenities: ['مطعم فاخر', 'سبا', 'حديقة تويلري', 'تصميم كلاسيكي'],
      lat: 48.8651,
      lng: 2.3279,
    },
    {
      id: 'hotel-paris-3',
      name: 'فندق شانغريلا باريس',
      nameEn: 'Shangri-La Hotel Paris',
      cityId: 'paris',
      stars: 5,
      rating: 4.7,
      reviewCount: 1876,
      pricePerNight: 3200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: "10 Avenue d'Iéna, Paris",
      addressEn: "10 Avenue d'Iéna, Paris",
      amenities: ['إطلالة على برج إيفل', 'سبا', 'مسبح', 'مطعم آسيوي'],
      lat: 48.8644,
      lng: 2.2932,
    },
    // Europe - London
    {
      id: 'hotel-london-1',
      name: 'فندق ذا سافوي',
      nameEn: 'The Savoy London',
      cityId: 'london',
      stars: 5,
      rating: 4.8,
      reviewCount: 3421,
      pricePerNight: 3500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800',
      address: 'Strand, London',
      addressEn: 'Strand, London',
      amenities: ['مسبح', 'سبا', 'مطعم', 'شاي بعد الظهر'],
      lat: 51.5100,
      lng: -0.1209,
    },
    {
      id: 'hotel-london-2',
      name: 'فندق كلاريدجز',
      nameEn: "Claridge's London",
      cityId: 'london',
      stars: 5,
      rating: 4.9,
      reviewCount: 2765,
      pricePerNight: 4200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1529290130-4ca3753253ae?w=800',
      address: 'Brook Street, Mayfair',
      addressEn: 'Brook Street, Mayfair',
      amenities: ['سبا', 'مطعم', 'بار', 'خدمة الخادم'],
      lat: 51.5125,
      lng: -0.1486,
    },
    {
      id: 'hotel-london-3',
      name: 'فندق ذا دورشستر',
      nameEn: 'The Dorchester',
      cityId: 'london',
      stars: 5,
      rating: 4.8,
      reviewCount: 2345,
      pricePerNight: 3800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800',
      address: 'Park Lane, London',
      addressEn: 'Park Lane, London',
      amenities: ['سبا', 'مطاعم', 'إطلالة على هايد بارك', 'بار'],
      lat: 51.5069,
      lng: -0.1536,
    },
    // Europe - Istanbul
    {
      id: 'hotel-istanbul-1',
      name: 'فندق فور سيزونز السلطان أحمد',
      nameEn: 'Four Seasons Sultanahmet',
      cityId: 'istanbul',
      stars: 5,
      rating: 4.9,
      reviewCount: 2543,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=800',
      address: 'Sultanahmet, Istanbul',
      addressEn: 'Sultanahmet, Istanbul',
      amenities: ['إطلالة على البوسفور', 'سبا', 'مطعم', 'حديقة تاريخية'],
      lat: 41.0054,
      lng: 28.9768,
    },
    {
      id: 'hotel-istanbul-2',
      name: 'فندق سيراجان بالاس كمبينسكي',
      nameEn: 'Çırağan Palace Kempinski',
      cityId: 'istanbul',
      stars: 5,
      rating: 4.8,
      reviewCount: 2876,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      address: 'Beşiktaş, Istanbul',
      addressEn: 'Beşiktaş, Istanbul',
      amenities: ['مسبح لا متناهي', 'سبا', 'قصر عثماني', 'شاطئ خاص'],
      lat: 41.0446,
      lng: 29.0234,
    },
    {
      id: 'hotel-istanbul-3',
      name: 'فندق رافلز إسطنبول',
      nameEn: 'Raffles Istanbul',
      cityId: 'istanbul',
      stars: 5,
      rating: 4.7,
      reviewCount: 1654,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      address: 'Zorlu Center, Istanbul',
      addressEn: 'Zorlu Center, Istanbul',
      amenities: ['سبا', 'مسبح', 'مطاعم', 'مركز تسوق'],
      lat: 41.0673,
      lng: 29.0156,
    },
    // Europe - Rome
    {
      id: 'hotel-rome-1',
      name: 'فندق هاسلر روما',
      nameEn: 'Hotel Hassler Roma',
      cityId: 'rome',
      stars: 5,
      rating: 4.8,
      reviewCount: 2134,
      pricePerNight: 2500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800',
      address: 'Piazza Trinità dei Monti, Rome',
      addressEn: 'Piazza Trinità dei Monti, Rome',
      amenities: ['إطلالة على الدرج الإسباني', 'مطعم ميشلان', 'سبا', 'حديقة سطح'],
      lat: 41.9058,
      lng: 12.4835,
    },
    {
      id: 'hotel-rome-2',
      name: 'فندق روما كافاليري',
      nameEn: 'Rome Cavalieri Waldorf Astoria',
      cityId: 'rome',
      stars: 5,
      rating: 4.7,
      reviewCount: 3245,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'Via Alberto Cadlolo, Rome',
      addressEn: 'Via Alberto Cadlolo, Rome',
      amenities: ['مسبح', 'سبا', 'حدائق', 'إطلالة على المدينة'],
      lat: 41.9271,
      lng: 12.4414,
    },
    // Europe - Barcelona
    {
      id: 'hotel-barcelona-1',
      name: 'فندق دبليو برشلونة',
      nameEn: 'W Barcelona',
      cityId: 'barcelona',
      stars: 5,
      rating: 4.6,
      reviewCount: 4321,
      pricePerNight: 1600,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800',
      address: 'Barceloneta Beach, Barcelona',
      addressEn: 'Barceloneta Beach, Barcelona',
      amenities: ['شاطئ', 'مسبح لا متناهي', 'سبا', 'نادي ليلي'],
      lat: 41.3686,
      lng: 2.1895,
    },
    {
      id: 'hotel-barcelona-2',
      name: 'فندق ماندارين أورينتال برشلونة',
      nameEn: 'Mandarin Oriental Barcelona',
      cityId: 'barcelona',
      stars: 5,
      rating: 4.8,
      reviewCount: 1876,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      address: 'Passeig de Gràcia, Barcelona',
      addressEn: 'Passeig de Gràcia, Barcelona',
      amenities: ['سبا', 'مطعم ميشلان', 'حديقة', 'تصميم عصري'],
      lat: 41.3916,
      lng: 2.1649,
    },
    // Europe - Amsterdam
    {
      id: 'hotel-amsterdam-1',
      name: 'فندق والدورف أستوريا أمستردام',
      nameEn: 'Waldorf Astoria Amsterdam',
      cityId: 'amsterdam',
      stars: 5,
      rating: 4.8,
      reviewCount: 1654,
      pricePerNight: 2400,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=800',
      address: 'Herengracht, Amsterdam',
      addressEn: 'Herengracht, Amsterdam',
      amenities: ['سبا', 'مطعم', 'إطلالة على القناة', 'حديقة'],
      lat: 52.3656,
      lng: 4.8897,
    },
    {
      id: 'hotel-amsterdam-2',
      name: 'فندق ذا ديلان أمستردام',
      nameEn: 'The Dylan Amsterdam',
      cityId: 'amsterdam',
      stars: 5,
      rating: 4.7,
      reviewCount: 987,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: 'Keizersgracht, Amsterdam',
      addressEn: 'Keizersgracht, Amsterdam',
      amenities: ['مطعم ميشلان', 'حديقة', 'إطلالة على القناة'],
      lat: 52.3698,
      lng: 4.8834,
    },
    // Asia - Maldives
    {
      id: 'hotel-maldives-1',
      name: 'منتجع سونيفا فوشي',
      nameEn: 'Soneva Fushi Resort',
      cityId: 'maldives',
      stars: 5,
      rating: 4.9,
      reviewCount: 1876,
      pricePerNight: 6500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=800',
      address: 'Baa Atoll, Maldives',
      addressEn: 'Baa Atoll, Maldives',
      amenities: ['فيلا خاصة', 'مسبح خاص', 'غوص', 'سبا فاخر'],
      lat: 5.1136,
      lng: 73.0676,
    },
    {
      id: 'hotel-maldives-2',
      name: 'منتجع أنانتارا كيهافا',
      nameEn: 'Anantara Kihavah Villas',
      cityId: 'maldives',
      stars: 5,
      rating: 4.9,
      reviewCount: 2134,
      pricePerNight: 7500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=800',
      address: 'Baa Atoll, Maldives',
      addressEn: 'Baa Atoll, Maldives',
      amenities: ['فيلا فوق الماء', 'مطعم تحت الماء', 'سبا', 'رياضات مائية'],
      lat: 5.1267,
      lng: 73.0598,
    },
    {
      id: 'hotel-maldives-3',
      name: 'منتجع كونراد المالديف',
      nameEn: 'Conrad Maldives Rangali Island',
      cityId: 'maldives',
      stars: 5,
      rating: 4.8,
      reviewCount: 3245,
      pricePerNight: 5500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?w=800',
      address: 'Rangali Island, Maldives',
      addressEn: 'Rangali Island, Maldives',
      amenities: ['مطعم تحت الماء', 'فيلا فوق الماء', 'سبا', 'غوص'],
      lat: 3.5546,
      lng: 72.6789,
    },
    // Asia - Tokyo
    {
      id: 'hotel-tokyo-1',
      name: 'فندق أمان طوكيو',
      nameEn: 'Aman Tokyo',
      cityId: 'tokyo',
      stars: 5,
      rating: 4.9,
      reviewCount: 1654,
      pricePerNight: 3800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800',
      address: 'Otemachi Tower, Tokyo',
      addressEn: 'Otemachi Tower, Tokyo',
      amenities: ['سبا ياباني', 'مسبح', 'إطلالة بانورامية', 'مطعم ياباني'],
      lat: 35.6884,
      lng: 139.7642,
    },
    {
      id: 'hotel-tokyo-2',
      name: 'فندق ماندارين أورينتال طوكيو',
      nameEn: 'Mandarin Oriental Tokyo',
      cityId: 'tokyo',
      stars: 5,
      rating: 4.8,
      reviewCount: 2876,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800',
      address: 'Nihonbashi, Tokyo',
      addressEn: 'Nihonbashi, Tokyo',
      amenities: ['سبا', 'مطعم ميشلان', 'إطلالة على طوكيو', 'مسبح'],
      lat: 35.6866,
      lng: 139.7743,
    },
    // Asia - Singapore
    {
      id: 'hotel-singapore-1',
      name: 'فندق مارينا باي ساندز',
      nameEn: 'Marina Bay Sands',
      cityId: 'singapore',
      stars: 5,
      rating: 4.7,
      reviewCount: 8765,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800',
      address: 'Marina Bay, Singapore',
      addressEn: 'Marina Bay, Singapore',
      amenities: ['مسبح سطح لا متناهي', 'كازينو', 'مركز تسوق', 'سبا'],
      lat: 1.2834,
      lng: 103.8607,
    },
    {
      id: 'hotel-singapore-2',
      name: 'فندق رافلز سنغافورة',
      nameEn: 'Raffles Singapore',
      cityId: 'singapore',
      stars: 5,
      rating: 4.9,
      reviewCount: 3456,
      pricePerNight: 3500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'Beach Road, Singapore',
      addressEn: 'Beach Road, Singapore',
      amenities: ['تراث تاريخي', 'سبا', 'مطاعم فاخرة', 'حديقة استوائية'],
      lat: 1.2945,
      lng: 103.8547,
    },
    // Asia - Bali
    {
      id: 'hotel-bali-1',
      name: 'منتجع فور سيزونز بالي',
      nameEn: 'Four Seasons Resort Bali at Sayan',
      cityId: 'bali',
      stars: 5,
      rating: 4.9,
      reviewCount: 2134,
      pricePerNight: 3200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800',
      address: 'Sayan, Ubud, Bali',
      addressEn: 'Sayan, Ubud, Bali',
      amenities: ['فيلا خاصة', 'مسبح لا متناهي', 'سبا', 'يوغا'],
      lat: -8.5014,
      lng: 115.2584,
    },
    {
      id: 'hotel-bali-2',
      name: 'منتجع أمانداري',
      nameEn: 'Amandari Resort',
      cityId: 'bali',
      stars: 5,
      rating: 4.8,
      reviewCount: 1543,
      pricePerNight: 4500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1545579133-99bb5ab189bd?w=800',
      address: 'Kedewatan, Ubud, Bali',
      addressEn: 'Kedewatan, Ubud, Bali',
      amenities: ['إطلالة على حقول الأرز', 'سبا', 'مسبح', 'تجارب ثقافية'],
      lat: -8.4867,
      lng: 115.2623,
    },
    {
      id: 'hotel-bali-3',
      name: 'منتجع سانت ريجيس بالي',
      nameEn: 'The St. Regis Bali Resort',
      cityId: 'bali',
      stars: 5,
      rating: 4.8,
      reviewCount: 2876,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      address: 'Nusa Dua, Bali',
      addressEn: 'Nusa Dua, Bali',
      amenities: ['شاطئ خاص', 'سبا', 'مسبح', 'خدمة الخادم'],
      lat: -8.8012,
      lng: 115.2305,
    },
    // Asia - Bangkok
    {
      id: 'hotel-bangkok-1',
      name: 'فندق ماندارين أورينتال بانكوك',
      nameEn: 'Mandarin Oriental Bangkok',
      cityId: 'bangkok',
      stars: 5,
      rating: 4.9,
      reviewCount: 4321,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800',
      address: 'Charoenkrung Road, Bangkok',
      addressEn: 'Charoenkrung Road, Bangkok',
      amenities: ['إطلالة على النهر', 'سبا', 'مطاعم فاخرة', 'مسبح'],
      lat: 13.7240,
      lng: 100.5133,
    },
    {
      id: 'hotel-bangkok-2',
      name: 'فندق بينينسولا بانكوك',
      nameEn: 'The Peninsula Bangkok',
      cityId: 'bangkok',
      stars: 5,
      rating: 4.8,
      reviewCount: 3654,
      pricePerNight: 1400,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'Charoennakorn Road, Bangkok',
      addressEn: 'Charoennakorn Road, Bangkok',
      amenities: ['مسبح', 'سبا', 'إطلالة على النهر', 'مطعم'],
      lat: 13.7167,
      lng: 100.5097,
    },
    // Asia - Hong Kong
    {
      id: 'hotel-hong-kong-1',
      name: 'فندق بينينسولا هونغ كونغ',
      nameEn: 'The Peninsula Hong Kong',
      cityId: 'hong-kong',
      stars: 5,
      rating: 4.9,
      reviewCount: 3876,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800',
      address: 'Tsim Sha Tsui, Hong Kong',
      addressEn: 'Tsim Sha Tsui, Hong Kong',
      amenities: ['سبا', 'مسبح سطح', 'مطاعم فاخرة', 'إطلالة على الميناء'],
      lat: 22.2950,
      lng: 114.1720,
    },
    {
      id: 'hotel-hong-kong-2',
      name: 'فندق ماندارين أورينتال هونغ كونغ',
      nameEn: 'Mandarin Oriental Hong Kong',
      cityId: 'hong-kong',
      stars: 5,
      rating: 4.8,
      reviewCount: 2654,
      pricePerNight: 2400,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800',
      address: 'Central, Hong Kong',
      addressEn: 'Central, Hong Kong',
      amenities: ['سبا', 'مطعم ميشلان', 'مسبح', 'صالة رياضية'],
      lat: 22.2822,
      lng: 114.1585,
    },
    // Americas - New York
    {
      id: 'hotel-new-york-1',
      name: 'فندق ذا بلازا نيويورك',
      nameEn: 'The Plaza Hotel New York',
      cityId: 'new-york',
      stars: 5,
      rating: 4.8,
      reviewCount: 5432,
      pricePerNight: 3200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800',
      address: 'Fifth Avenue, New York',
      addressEn: 'Fifth Avenue, New York',
      amenities: ['إطلالة على سنترال بارك', 'سبا', 'مطاعم', 'تراث تاريخي'],
      lat: 40.7644,
      lng: -73.9742,
    },
    {
      id: 'hotel-new-york-2',
      name: 'فندق فور سيزونز نيويورك',
      nameEn: 'Four Seasons New York Downtown',
      cityId: 'new-york',
      stars: 5,
      rating: 4.7,
      reviewCount: 2876,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800',
      address: 'Tribeca, New York',
      addressEn: 'Tribeca, New York',
      amenities: ['سبا', 'مطعم', 'صالة رياضية', 'إطلالة على المدينة'],
      lat: 40.7186,
      lng: -74.0060,
    },
    {
      id: 'hotel-new-york-3',
      name: 'فندق سانت ريجيس نيويورك',
      nameEn: 'The St. Regis New York',
      cityId: 'new-york',
      stars: 5,
      rating: 4.8,
      reviewCount: 3245,
      pricePerNight: 3500,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: 'Fifth Avenue, New York',
      addressEn: 'Fifth Avenue, New York',
      amenities: ['خدمة الخادم', 'سبا', 'مطعم', 'تصميم كلاسيكي'],
      lat: 40.7616,
      lng: -73.9751,
    },
    // Americas - Miami
    {
      id: 'hotel-miami-1',
      name: 'فندق فور سيزونز ميامي',
      nameEn: 'Four Seasons Hotel Miami',
      cityId: 'miami',
      stars: 5,
      rating: 4.7,
      reviewCount: 2134,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=800',
      address: 'Brickell, Miami',
      addressEn: 'Brickell, Miami',
      amenities: ['مسبح', 'سبا', 'مطعم', 'إطلالة على الخليج'],
      lat: 25.7617,
      lng: -80.1918,
    },
    {
      id: 'hotel-miami-2',
      name: 'فندق فاينا ميامي بيتش',
      nameEn: 'Faena Hotel Miami Beach',
      cityId: 'miami',
      stars: 5,
      rating: 4.8,
      reviewCount: 1876,
      pricePerNight: 2400,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800',
      address: 'Collins Avenue, Miami Beach',
      addressEn: 'Collins Avenue, Miami Beach',
      amenities: ['شاطئ خاص', 'سبا', 'مطعم', 'نادي ليلي'],
      lat: 25.8193,
      lng: -80.1235,
    },
    // Americas - Cancun
    {
      id: 'hotel-cancun-1',
      name: 'فندق نيزوك كانكون',
      nameEn: 'NIZUC Resort & Spa',
      cityId: 'cancun',
      stars: 5,
      rating: 4.9,
      reviewCount: 2543,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=800',
      address: 'Punta Nizuc, Cancun',
      addressEn: 'Punta Nizuc, Cancun',
      amenities: ['شاطئ خاص', 'سبا', 'مطاعم', 'غوص'],
      lat: 21.0305,
      lng: -86.7827,
    },
    {
      id: 'hotel-cancun-2',
      name: 'فندق ريتز كارلتون كانكون',
      nameEn: 'The Ritz-Carlton Cancun',
      cityId: 'cancun',
      stars: 5,
      rating: 4.8,
      reviewCount: 3876,
      pricePerNight: 1800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800',
      address: 'Hotel Zone, Cancun',
      addressEn: 'Hotel Zone, Cancun',
      amenities: ['شاطئ', 'سبا', 'مسابح', 'رياضات مائية'],
      lat: 21.0928,
      lng: -86.7637,
    },
    // Americas - Los Angeles
    {
      id: 'hotel-los-angeles-1',
      name: 'فندق بيفرلي هيلز',
      nameEn: 'The Beverly Hills Hotel',
      cityId: 'los-angeles',
      stars: 5,
      rating: 4.8,
      reviewCount: 3654,
      pricePerNight: 2800,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=800',
      address: 'Sunset Boulevard, Beverly Hills',
      addressEn: 'Sunset Boulevard, Beverly Hills',
      amenities: ['مسبح', 'سبا', 'حدائق استوائية', 'مطعم'],
      lat: 34.0816,
      lng: -118.4134,
    },
    {
      id: 'hotel-los-angeles-2',
      name: 'فندق شاتو مارمونت',
      nameEn: 'Chateau Marmont',
      cityId: 'los-angeles',
      stars: 5,
      rating: 4.6,
      reviewCount: 1987,
      pricePerNight: 2200,
      currency: 'SAR',
      image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800',
      address: 'Sunset Boulevard, West Hollywood',
      addressEn: 'Sunset Boulevard, West Hollywood',
      amenities: ['مسبح', 'حديقة خاصة', 'مطعم', 'تراث هوليوود'],
      lat: 34.0984,
      lng: -118.3687,
    },
  ];

  private numericIdMap: Record<string, string> = {};

  constructor() {
    this.mockHotels.forEach((hotel, index) => {
      this.numericIdMap[String(index + 1)] = hotel.id;
    });
  }

  private resolveHotelId(id: string): string {
    if (this.numericIdMap[id]) {
      return this.numericIdMap[id];
    }
    return id;
  }

  private translateAmenity(amenity: string): string {
    const translations: Record<string, string> = {
      'مسبح': 'Swimming Pool',
      'سبا': 'Spa',
      'مطعم': 'Restaurant',
      'واي فاي مجاني': 'Free WiFi',
      'موقف سيارات': 'Parking',
      'صالة رياضية': 'Gym',
      'إطلالة على البحر': 'Sea View',
      'شاطئ خاص': 'Private Beach',
      'مطاعم فاخرة': 'Fine Dining',
      'سبا عالمي': 'World-class Spa',
      'مسبح لا متناهي': 'Infinity Pool',
      'خدمة الغرف': 'Room Service',
      'أكواريوم': 'Aquarium',
      'حديقة مائية': 'Water Park',
      'مطاعم متنوعة': 'Multiple Restaurants',
      'إطلالة بانورامية': 'Panoramic View',
      'إطلالة على الحرم': 'Haram View',
      'خدمة الخادم الشخصي': 'Butler Service',
      'مواقف سيارات': 'Parking',
      'إطلالة على الحرم النبوي': "Prophet's Mosque View",
      'قريب من الحرم': 'Near Haram',
      'رياضات مائية': 'Water Sports',
      'حدائق استوائية': 'Tropical Gardens',
      'شاطئ': 'Beach',
      'نادي للأطفال': 'Kids Club',
      'مطعم ميشلان': 'Michelin Restaurant',
      'إطلالة على برج إيفل': 'Eiffel Tower View',
      'خدمة الخادم': 'Butler Service',
      'حديقة تويلري': 'Tuileries Garden',
      'تصميم كلاسيكي': 'Classic Design',
      'مطعم آسيوي': 'Asian Restaurant',
      'شاي بعد الظهر': 'Afternoon Tea',
      'بار': 'Bar',
      'إطلالة على هايد بارك': 'Hyde Park View',
      'إطلالة على البوسفور': 'Bosphorus View',
      'حديقة تاريخية': 'Historic Garden',
      'قصر عثماني': 'Ottoman Palace',
      'مركز تسوق': 'Shopping Mall',
      'إطلالة على الدرج الإسباني': 'Spanish Steps View',
      'حديقة سطح': 'Rooftop Garden',
      'حدائق': 'Gardens',
      'إطلالة على المدينة': 'City View',
      'نادي ليلي': 'Nightclub',
      'تصميم عصري': 'Modern Design',
      'إطلالة على القناة': 'Canal View',
      'حديقة': 'Garden',
      'فيلا خاصة': 'Private Villa',
      'مسبح خاص': 'Private Pool',
      'غوص': 'Diving',
      'سبا فاخر': 'Luxury Spa',
      'فيلا فوق الماء': 'Overwater Villa',
      'مطعم تحت الماء': 'Underwater Restaurant',
      'سبا ياباني': 'Japanese Spa',
      'مطعم ياباني': 'Japanese Restaurant',
      'إطلالة على طوكيو': 'Tokyo View',
      'مسبح سطح لا متناهي': 'Rooftop Infinity Pool',
      'كازينو': 'Casino',
      'تراث تاريخي': 'Historic Heritage',
      'حديقة استوائية': 'Tropical Garden',
      'يوغا': 'Yoga',
      'إطلالة على حقول الأرز': 'Rice Terrace View',
      'تجارب ثقافية': 'Cultural Experiences',
      'إطلالة على النهر': 'River View',
      'مسبح سطح': 'Rooftop Pool',
      'إطلالة على الميناء': 'Harbor View',
      'إطلالة على سنترال بارك': 'Central Park View',
      'مطاعم': 'Restaurants',
      'إطلالة على الخليج': 'Bay View',
      'مسابح': 'Pools',
      'تراث هوليوود': 'Hollywood Heritage',
      'حديقة خاصة': 'Private Garden',
      'ملاعب تنس': 'Tennis Courts',
      'ملاعب رياضية': 'Sports Facilities',
      'مطعم فاخر': 'Fine Dining Restaurant',
    };
    return translations[amenity] || amenity;
  }

  async searchHotels(params: any) {
    let results = this.mockHotels;

    if (params.cityId) {
      results = results.filter(h => h.cityId === params.cityId);
    }

    if (params.query) {
      const query = params.query.toLowerCase();
      results = results.filter(
        h =>
          h.name.toLowerCase().includes(query) ||
          h.nameEn.toLowerCase().includes(query) ||
          h.cityId.toLowerCase().includes(query),
      );
    }

    if (params.minPrice) {
      results = results.filter(h => h.pricePerNight >= params.minPrice);
    }

    if (params.maxPrice) {
      results = results.filter(h => h.pricePerNight <= params.maxPrice);
    }

    if (params.stars) {
      results = results.filter(h => h.stars >= params.stars);
    }

    return results.map(hotel => ({
      id: hotel.id,
      nameAr: hotel.name,
      nameEn: hotel.nameEn,
      cityId: hotel.cityId,
      stars: hotel.stars,
      rating: hotel.rating,
      reviewCount: hotel.reviewCount,
      location: {
        lat: hotel.lat,
        lng: hotel.lng,
        addressAr: hotel.address,
        addressEn: hotel.addressEn,
        distanceToCenterKm: Math.round(Math.random() * 10 * 10) / 10,
      },
      thumbnail: hotel.image,
      images: [hotel.image, hotel.image, hotel.image],
      amenities: hotel.amenities.map(a => this.translateAmenity(a)),
      amenitiesAr: hotel.amenities,
      amenitiesEn: hotel.amenities.map(a => this.translateAmenity(a)),
      minPrice: hotel.pricePerNight,
      pricePerNight: hotel.pricePerNight,
      priceSar: hotel.pricePerNight,
      totalPrice: hotel.pricePerNight * (params.nights || 3),
      currency: hotel.currency,
      freeCancellation: true,
      breakfastIncluded: hotel.stars >= 4,
      rooms: this.generateRooms(hotel.id, hotel.pricePerNight),
    }));
  }

  private generateRooms(hotelId: string, basePrice: number) {
    return [
      {
        id: `${hotelId}-room-1`,
        nameAr: 'غرفة ديلوكس',
        nameEn: 'Deluxe Room',
        priceSar: basePrice,
        pricePerNight: basePrice,
        totalPrice: basePrice * 3,
        currency: 'SAR',
        refundable: true,
        breakfast: true,
        breakfastIncluded: true,
        freeCancellation: true,
        capacity: 2,
        maxAdults: 2,
        maxChildren: 1,
        size: 35,
        sizeSqm: 35,
        bedType: 'king',
        bedTypeAr: 'سرير كينج',
        bedTypeEn: 'King Bed',
        amenities: ['WiFi', 'TV', 'Mini Bar', 'Safe'],
        amenitiesAr: ['واي فاي', 'تلفزيون', 'ميني بار', 'خزنة'],
        amenitiesEn: ['WiFi', 'TV', 'Mini Bar', 'Safe'],
        images: [
          'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
        ],
      },
      {
        id: `${hotelId}-room-2`,
        nameAr: 'جناح تنفيذي',
        nameEn: 'Executive Suite',
        priceSar: Math.round(basePrice * 1.5),
        pricePerNight: Math.round(basePrice * 1.5),
        totalPrice: Math.round(basePrice * 1.5) * 3,
        currency: 'SAR',
        refundable: true,
        breakfast: true,
        breakfastIncluded: true,
        freeCancellation: true,
        capacity: 4,
        maxAdults: 3,
        maxChildren: 2,
        size: 60,
        sizeSqm: 60,
        bedType: 'king-twin',
        bedTypeAr: 'سرير كينج + سريرين',
        bedTypeEn: 'King Bed + Twin Beds',
        amenities: ['WiFi', 'TV', 'Mini Bar', 'Safe', 'Lounge Access'],
        amenitiesAr: [
          'واي فاي',
          'تلفزيون',
          'ميني بار',
          'خزنة',
          'دخول اللاونج',
        ],
        amenitiesEn: ['WiFi', 'TV', 'Mini Bar', 'Safe', 'Lounge Access'],
        images: [
          'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800',
        ],
      },
      {
        id: `${hotelId}-room-3`,
        nameAr: 'غرفة قياسية',
        nameEn: 'Standard Room',
        priceSar: Math.round(basePrice * 0.7),
        pricePerNight: Math.round(basePrice * 0.7),
        totalPrice: Math.round(basePrice * 0.7) * 3,
        currency: 'SAR',
        refundable: false,
        breakfast: false,
        breakfastIncluded: false,
        freeCancellation: false,
        capacity: 2,
        maxAdults: 2,
        maxChildren: 0,
        size: 25,
        sizeSqm: 25,
        bedType: 'queen',
        bedTypeAr: 'سرير كوين',
        bedTypeEn: 'Queen Bed',
        amenities: ['WiFi', 'TV'],
        amenitiesAr: ['واي فاي', 'تلفزيون'],
        amenitiesEn: ['WiFi', 'TV'],
        images: [
          'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
        ],
      },
      {
        id: `${hotelId}-room-4`,
        nameAr: 'جناح عائلي',
        nameEn: 'Family Suite',
        priceSar: Math.round(basePrice * 2),
        pricePerNight: Math.round(basePrice * 2),
        totalPrice: Math.round(basePrice * 2) * 3,
        currency: 'SAR',
        refundable: true,
        breakfast: true,
        breakfastIncluded: true,
        freeCancellation: true,
        capacity: 6,
        maxAdults: 4,
        maxChildren: 3,
        size: 90,
        sizeSqm: 90,
        bedType: 'king-two-doubles',
        bedTypeAr: 'سرير كينج + سريرين مزدوجين',
        bedTypeEn: 'King Bed + Two Double Beds',
        amenities: ['WiFi', 'TV', 'Mini Bar', 'Safe', 'Kitchen', 'Living Area'],
        amenitiesAr: [
          'واي فاي',
          'تلفزيون',
          'ميني بار',
          'خزنة',
          'مطبخ',
          'غرفة معيشة',
        ],
        amenitiesEn: [
          'WiFi',
          'TV',
          'Mini Bar',
          'Safe',
          'Kitchen',
          'Living Area',
        ],
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
        ],
      },
    ];
  }

  async getHotelDetails(id: string) {
    const resolvedId = this.resolveHotelId(id);
    const hotel = this.mockHotels.find(h => h.id === resolvedId);

    if (!hotel) {
      const firstHotel = this.mockHotels[0];
      return this.buildHotelDetails(firstHotel);
    }

    return this.buildHotelDetails(hotel);
  }

  private buildHotelDetails(hotel: any) {
    return {
      id: hotel.id,
      nameAr: hotel.name,
      nameEn: hotel.nameEn,
      cityId: hotel.cityId,
      stars: hotel.stars,
      rating: hotel.rating,
      reviewCount: hotel.reviewCount,
      location: {
        lat: hotel.lat,
        lng: hotel.lng,
        addressAr: hotel.address,
        addressEn: hotel.addressEn,
        distanceToCenterKm: Math.round(Math.random() * 10 * 10) / 10,
      },
      thumbnail: hotel.image,
      images: [
        hotel.image,
        'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800',
        'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800',
        'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800',
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800',
      ],
      amenities: hotel.amenities.map((a: string) => this.translateAmenity(a)),
      amenitiesAr: hotel.amenities,
      amenitiesEn: hotel.amenities.map((a: string) => this.translateAmenity(a)),
      minPrice: hotel.pricePerNight,
      descriptionAr:
        'فندق فاخر في قلب المدينة مع خدمات من الدرجة الأولى ومرافق عالمية المستوى. يوفر الفندق تجربة إقامة استثنائية مع غرف مصممة بأناقة وإطلالات خلابة ومطاعم راقية.',
      descriptionEn:
        'Luxury hotel in the heart of the city with world-class services and facilities. The hotel offers an exceptional stay experience with elegantly designed rooms, stunning views, and fine dining restaurants.',
      pricePerNight: hotel.pricePerNight,
      priceSar: hotel.pricePerNight,
      currency: hotel.currency,
      freeCancellation: true,
      breakfastIncluded: hotel.stars >= 4,
      checkInTime: '15:00',
      checkOutTime: '12:00',
      policies: {
        cancellation: 'Free cancellation up to 24 hours before check-in',
        cancellationAr: 'إلغاء مجاني حتى 24 ساعة قبل تسجيل الوصول',
        pets: 'Pets not allowed',
        petsAr: 'غير مسموح بالحيوانات الأليفة',
        smoking: 'Non-smoking rooms available',
        smokingAr: 'غرف لغير المدخنين متاحة',
      },
      rooms: this.generateRooms(hotel.id, hotel.pricePerNight),
    };
  }

  async getHotelsByCity(cityId: string) {
    return this.searchHotels({ cityId });
  }

  async getAllCities() {
    const cities = [...new Set(this.mockHotels.map(h => h.cityId))];
    return cities.map(cityId => ({
      id: cityId,
      hotelCount: this.mockHotels.filter(h => h.cityId === cityId).length,
    }));
  }
}
